version: '3.9'

services:
  postgres:
    image: postgres:13.2
    container_name: local_keycloak_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
  keycloak:
    # build:
    #   context: keycloak
    image: quay.io/keycloak/keycloak:21.1.0
    container_name: local_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --db-url "jdbc:postgresql://postgres:5432/keycloak" --db-username=${POSTGRESQL_USER} --db-password=${POSTGRESQL_PASS} --db=postgres --features=token-exchange
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: always
